cursor #e6e0ef
cursor_text_color #c9c4d3

foreground            #e6e0ef
background            #14121c
selection_foreground  #382a49
selection_background  #d3bfe6
url_color             #c9beff

color0   #14121c
color1   #e15143
color2   #6ed673
color3   #dbd87b
color4   #896fe6
color5   #9e98bf
color6   #c9beff
color7   #abb2bf
color8   #5c6370
color9   #e0685f
color10  #86e08a
color11  #e8e597
color12  #d7ccff
color13  #756cd0
color14  #846cb7
color15  #ffffff
